export const FETCH_PLEX_PIN = "FETCH_PLEX_PIN"
export const RECEIVED_PLEX_PIN = "RECEIVED_PLEX_PIN"
export const PLEX_PIN_ERROR = "PLEX_PIN_ERROR"

export const CHECK_PLEX_PIN = "CHECK_PLEX_PIN"
export const CHECK_PLEX_PIN_SUCESS = "CHECK_PLEX_PIN_SUCESS"
export const CHECK_PLEX_PIN_ERROR = "CHECK_PLEX_PIN_ERROR"

export const ERROR_PIN_NOT_FOUND = "ERROR_PIN_NOT_FOUND"
export const ERROR_PIN_UNAUTHORIZED = "ERROR_PIN_UNAUTHORIZED"

export const PLEX_SERVER_FETCHING = "PLEX_SERVER_FETCHING"
export const PLEX_SERVER_RECEIVED = "PLEX_SERVER_RECEIVED"
export const PLEX_SERVER_ERROR = "PLEX_SERVER_ERROR"
export const PLEX_SERVER_SELECT = "PLEX_SERVER_SELECT"
export const PLEX_SERVER_CONNECTION_SELECT = "PLEX_SERVER_CONNECTION_SELECT"

export const PLEX_SERVER_SET = "PLEX_SERVER_SET"
